name: was_gibts_in
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  dropdown_button2: ^2.3.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  get: ^4.6.5
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.1.0
  flutter_zoom_drawer: ^3.1.1
  step_progress_indicator: ^1.0.2
  permission_handler: ^11.1.0
  location: ^5.0.3
  firebase_core: ^2.24.2
  sliding_up_panel: ^2.0.0+1
  fluttertoast: ^8.2.4
  flutter_screenutil: ^5.9.0
  google_maps_flutter: ^2.5.1
  geolocator: ^10.1.0
  http: ^1.1.2
  geocoding: ^2.1.1
  cloud_firestore: ^4.14.0
  geoflutterfire2: ^2.3.15
  flutter_polyline_points: ^2.0.0
  shimmer: ^3.0.0
  firebase_auth: ^4.16.0
  shared_preferences: ^2.3.2
  uuid: ^4.3.3
  dotted_line: ^3.2.2
  app_settings: ^5.1.1
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  lottie: ^3.1.2
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgImage/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/montserrat/Montserrat-Black.ttf
          weight: 900

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ""
