// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqXRJu0ZHiTT3MgNZLVHUEjLjfyPVENiA',
    appId: '1:430350547051:web:97b84bb52ec2458077192e',
    messagingSenderId: '430350547051',
    projectId: 'was-gibts-in-87c3d',
    authDomain: 'was-gibts-in-87c3d.firebaseapp.com',
    storageBucket: 'was-gibts-in-87c3d.appspot.com',
    measurementId: 'G-PSYM9KBYNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpEOsbudpoMtrHntX4E5cPPmADxNnn_Lk',
    appId: '1:430350547051:android:0eb1efabecb17e6377192e',
    messagingSenderId: '430350547051',
    projectId: 'was-gibts-in-87c3d',
    storageBucket: 'was-gibts-in-87c3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDa8gSQEi7MKrAI1cHHbmSMWTpjPvTx7Y',
    appId: '1:430350547051:ios:759650a8647e2eb777192e',
    messagingSenderId: '430350547051',
    projectId: 'was-gibts-in-87c3d',
    storageBucket: 'was-gibts-in-87c3d.appspot.com',
    iosBundleId: 'com.example.wasGibtsIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDa8gSQEi7MKrAI1cHHbmSMWTpjPvTx7Y',
    appId: '1:430350547051:ios:b2fe0da09f65ce6f77192e',
    messagingSenderId: '430350547051',
    projectId: 'was-gibts-in-87c3d',
    storageBucket: 'was-gibts-in-87c3d.appspot.com',
    iosBundleId: 'com.example.wasGibtsIn.RunnerTests',
  );
}
